Update dyno_panel.py
Bruin-SuperMileage/EV pull request #5
Opened 2020-09-08 23:48 UTC by MiraynaMckinney

2020-09-09 00:05 UTC, ashvinnagarajan requested changes
Thanks for opening this PR @MiraynaMckinney! Check out the comments below

2020-09-09 00:05 UTC, ashvinnagarajan commented on dyno/panda/dyno_panel.py
> +window.after(loop_speed, update_labels, check_ack)
This wont work they way you think. Window.after( ) accepts two arguments. The first argument is a integer speed that dictates how often the second argument, a function, is called. Can't add more arguments.

2020-09-09 00:05 UTC, ashvinnagarajan commented on dyno/panda/dyno_panel.py
> +push_button.bind("<Button-1>", mcu_flag)
We can just add the mcu_acknowledged = false statement to the push_config function instead of defining a separate function and binding the button

2020-09-09 00:05 UTC, ashvinnagarajan commented on dyno/panda/dyno_panel.py
> +            print("ACK=SUCCESS;")
The microcontroller is going to be printing this message. Not the lattepanda. We want to change this line to parse the input from the microcontroller

2020-09-09 00:06 UTC, ashvinnagarajan commented
As discussed, lets talk about these comments during the next Special Projects shop hours!!

2020-09-09 00:14 UTC, abdullahelqaq reviewed
Should be good to go after addressing Ash's comments! Also, could you add a Summary to the PR? That way, reviewers can get some context as to what this PR accomplishes, and it also makes PRs easier to look over in the future if needed. I would also recommend changing the name of the PR from _Update dyno_panel.py_ to something more descriptive like _Add support for ACK acknowledgement to Dyno panel_. Great stuff!

2020-09-13 19:36 UTC, anaymehta commented on dyno/panda/dyno_panel.py
> +        if data:
Maybe something like data_read would be clearer here?

2020-09-20 17:43 UTC, ashvinnagarajan requested changes
Looking much better! I added a few more small comments but its looking pretty much ready!

2020-09-20 17:43 UTC, ashvinnagarajan commented on dyno/panda/dyno_panel.py
> +    read_data;
This should be moved into the `if READ_SERIAL_ON` if statement

2020-09-20 17:43 UTC, ashvinnagarajan commented on dyno/panda/dyno_panel.py
> +    mcu_flag
Whats this line supposed to do? It will probably throw an error. Did you mean mcu_flag( )?

2020-09-20 17:43 UTC, ashvinnagarajan commented on dyno/panda/dyno_panel.py
> +    mcu_flag
We dont need a function to do this. Just write `mcu_acknowledged = False` here

2020-09-20 17:43 UTC, ashvinnagarajan commented on dyno/panda/dyno_panel.py
> +def read_data():
Please rename this function to something more appropriate. Maybe check_acknowledge( )?

2020-09-20 17:43 UTC, ashvinnagarajan commented on dyno/panda/dyno_panel.py
> +        if "ack=200" in data:
`ack=200;`

2020-10-04 23:39 UTC, ashvinnagarajan reviewed
Just one more small fix to add quotes. Otherwise looks good

2020-10-04 23:39 UTC, ashvinnagarajan commented on dyno/panda/dyno_panel.py
> +        if ack=200;
This needs to have quotes. Like `if ack = "200;"`

2020-10-05 00:55 UTC, ashvinnagarajan approved these changes
Looks good!

2020-10-05 18:23 UTC, abdullahelqaq approved these changes

2020-10-11 04:40 UTC, merged